import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '@components/templates/Layout';
import Container from '@src/components/templates/Container';
import Grid from '@src/components/templates/Grid';
import ArticleCard from '@components/molecules/ArticleCard';
import Heading from '@components/atoms/Heading';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container>
          <Heading level={1} align="center">
            9人
          </Heading>
          <Grid
            col={1}
            colPc={2}
            items={[
              {
                id: '1',
                item: (
                  <ArticleCard
                    title={'test'}
                    date={'2021/03/21'}
                    name="大石"
                    content="test test"
                    href="/"
                  />
                ),
              },
              {
                id: '2',
                item: (
                  <ArticleCard
                    title={'test'}
                    date={'2021/03/21'}
                    name="大石"
                    content="test test"
                    href="/"
                  />
                ),
              },
              {
                id: '3',
                item: (
                  <ArticleCard
                    title={'test'}
                    date={'2021/03/21'}
                    name="大石"
                    content="test test"
                    href="/"
                  />
                ),
              },
            ]}
          ></Grid>
        </Container>
      </Layout>
    </>
  );
};

export default Home;
