import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '@components/templates/Layout';
import Container from '@src/components/templates/Container';
import ArticleCard from '@components/molecules/ArticleCard';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container>
          <h1>test</h1>
          <ArticleCard
            title={'test'}
            date={'2021/03/21'}
            name="大石"
            content="test test"
            href="/"
          />
        </Container>
      </Layout>
    </>
  );
};

export default Home;
